name: Tests
on:
  schedule:
  - cron: 0 0 * * * # daily
  push:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
           java-version: '8'
           distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: compile java
        run: ./gradlew compileJava --no-daemon
      - name: run tests
        run: ./gradlew test --no-daemon
